### ISSUE TITLE
Missing infos on possible drone status fields

### ISSUE THREAD

**Issue by StatusPro-ziegelt** [mike1pol/drone-rocket#7]
Hi everyone,

I just saw on https://github.com/drone/drone-plugin-index/blob/main/plugins/rocket/original.md that there are some (here) undocumented flags from drone, that I could use to deploy a message to rocket chat.

Basically my integration is working - thanks for this wonderful plugin.

Unfortunately, I won't get the configured info.
Maybe I'm using it wrong ?

**Comment by StatusPro-ziegelt** [comment]
![image](https://user-images.githubusercontent.com/102592102/188241434-787c3c76-87bd-48fe-957d-d4d83c372644.png)

**Comment by StatusPro-ziegelt** [comment]
```
kind: pipeline
type: docker
name: notify-rocket-chat-push-prod

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: notify-build-finished
    image: mike1pol/drone-rocket
    settings:
      url:
        from_secret: ROCKET_URL
      user_id:
        from_secret: ROCKET_USER
      token:
        from_secret: ROCKET_TOKEN
      channel:
        from_secret: ROCKET_CHANNEL
      message: |
        DroneCI Pipeline
        Status: {{ build.status }} for #{{ build.number }} / {{ build.tag }}
        {{ repo.name }} : {{ commit.author }} {{ build.event }} {{ commit.sha }} @ {{ commit.branch }}
        Started: {{ build.started}}   Finished: {{ build.finished }}
        {{ commit.message }}
        {{ build.link }}

depends_on:
- deploy-prod-cluster
```
